### ISSUE TITLE
Virtual puzzle

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/yadism#89]
Some virtual contributions to DIS seems missing from calculations, there will be for sure a good reason but we haven't found it:

- photon - gluon @ NLO 
- quark loop @ NNLO

![image](https://user-images.githubusercontent.com/10830876/99379315-ccd4cb00-28c8-11eb-9592-da68208b547f.png) ![image](https://user-images.githubusercontent.com/10830876/99379345-d827f680-28c8-11eb-8d3e-930389562982.png)

In particular the first diagram will make a virtual correction proportional to nf at NLO, and both to nf^2 at NNLO, but it is easy to see that there is nothing like that around...

**Comment by Qdashkin** [comment]
Well, if I am not mistaken, the first diagram (set of diagrams where one have a color singlet connect to the loop and a gluon) is zero because of color (Tr(T) = 0), I believe. 
The second, I believe, there should be a sum of such diagrams (different direction of the fermion flow at least). My suggestion that it is zero. I will show the solution later.

**Comment by Qdashkin** [comment]
I have explicitly calculated the second diagrams (that it is I have generated V(gamma,Z,W)->gg @ NLO QCD). They are zero. I guess it is Furry theorem in the end. That is, I **see** it is that if you decompose gluon into U1 and U(N), the latter will couple only to the gluons (which you don't have) while U1, photon which couples only to quarks, which is unphysical particle since ~1/N. But there it is three photons, basically.

**Comment by Qdashkin** [comment]
I emphasis **see** since I am not sure in the end that my explanation is correct (but results are!) since I have not looked at the intermediate steps of mine code.

**Comment by AleCandido** [comment]
Thank you @Qdashkin and @stefanoforte this has been solved.

The second one was really more cumbersome for us, but at the end of the day it's really Furry's theorem, even if you would require nor the proof with charge conjugation neither the one with Lorentz invariance, since the photon is off-shell.

Then the solution has been found in generic proof of Furry's theorem on quark loops in Itzykson-Zuber p.276, eq. 6-33 and 6-34, fig. 6-11.

**Comment by Qdashkin** [comment]
I mean I don't know why it was ``cumbersome'' since I have computed it and gave a solution...
